In [19]:
import pandas as pd
import numpy as np
import pickle
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler

# Test for Submission

In [ ]:
num_feature = 5

print('INFO: Begin preprocessing...')
selected_col = ['hash', 'x_entry', 'y_entry', 'x_exit', 'y_exit']
test = pd.read_csv('data_test.csv').drop('Unnamed: 0', axis=1)
test = test[selected_col]

all_hash = test.hash.unique()
all_ped_data = []

hash_count = all_hash.shape[0]
counter = 1
print('INFO: Separate data by Hash. Total hash: {}'.format(hash_count))

for hsh in all_hash:
    filtered_data = train.loc[train.hash == hsh].drop('hash', axis=1).values

    tmp_arr = []
    for row in filtered_data:
        tmp_arr.append(list(row[:2]))
        tmp_arr.append([row[2], row[3]])

    tmp_arr = np.array(tmp_arr).T

    if tmp_arr.shape[1] <= num_feature:
        count_miss = num_feature - tmp_arr.shape[1] + 1
        arrT = tmp_arr.T
        first_elm = np.array([arrT[0]])
        for x in range(count_miss):
            arrT = np.concatenate((first_elm, arrT))

    elif tmp_arr.shape[1] > num_feature + 1:
        arrT = tmp_arr.T
        arrT = arrT[-(num_feature+1):]
        
    tmp_arr = arrT[:-1].T
    all_ped_data.append(tmp_arr)

    print("INFO: Progress: {}".format(counter), end="\r")
    counter += 1
    
all_ped_data = np.array(all_ped_data)

In [ ]:
test_ready_data = (all_hash, all_ped_data)
pickle.dump(test_ready_data, open("misc/test_ready_data.pickle", "wb"))

In [3]:
# Load Test Ready data
test_hash, test_ped_data = pickle.load(open("misc/test_ready_data.pickle", "rb"))
# test_ped_data

In [5]:
# Load Model
num_feature = 5
rnn_size = 512

model = Sequential()
model.add(
    LSTM(rnn_size, 
         input_shape=(2, num_feature)
    )
)
model.add(Dense(2))
model.load_weights('misc/keras_lstm.h5')

In [11]:
model.predict(test_ped_data)

array([[ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       ...,
       [ 532227.8 , -532199.75],
       [ 532227.8 , -532199.75],
       [ 532227.8 , -532199.75]], dtype=float32)

# Test from Training

In [13]:
trained_ready_data = pickle.load(open('misc/trained_ready_data.pickle', 'rb'))
training_X, training_Y, dev_X, dev_Y, testing_X, testing_Y = trained_ready_data

# scaler = pickle.load(open('misc/scaler.pickle', 'rb'))

In [14]:
np.array(training_X).shape[1]

2

In [15]:
# Load model
num_feature = 5
rnn_size = 512

model = Sequential()
model.add(
    LSTM(rnn_size, 
         input_shape=(2, num_feature)
    )
)
model.add(Dense(2))
model.load_weights('misc/keras_lstm.h5')

In [16]:
testing_X = np.array(testing_X)
testing_Y = np.array(testing_Y)

In [17]:
model.predict(testing_X[0:10])

array([[ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.94, -532199.75],
       [ 532227.8 , -532199.75],
       [ 532227.8 , -532199.75]], dtype=float32)

In [18]:
testing_Y[0:10]

array([[  3758992.03731095, -19296150.48371874],
       [  3754451.31528149, -19367729.23896086],
       [  3758905.20810813, -19295817.17516739],
       [  3746390.67095315, -19355258.48919743],
       [  3744597.31395647, -19320932.7785616 ],
       [  3753822.3601585 , -19191282.67027628],
       [  3758314.10161201, -19235202.80750339],
       [  3761192.82364393, -19351106.96029497],
       [  3761210.63476245, -19351257.6670844 ],
       [  3766718.7231669 , -19347966.11021282]])

In [ ]:
scaler.inverse_transform(testing_Y)

## Explore

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[6,7,8]])
arrT = arr.T
first_elm = arrT[0]
for x in range(3):
    arrT = np.concatenate((np.array([[1,6]]), arrT))

arr = arrT.T

In [ ]:
np.concatenate(([[1,6]], arr.T))

In [ ]:
arr.T

In [ ]:
dct = dict(a=1,b=2,c=3)
print(dct)

for k, v in dct.items():
    dct[k] = 5

print(dct)

In [64]:
ax = np.array([
    [[1,2,3,4,5],
     [6,7,8,9,10]],
    [[11,12,13,14,15],
     [16,17,18,19,20]],
    [[21,22,23,24,25],
     [26,27,28,29,30]]
])
ay = np.array([
    [1,2,1],
    [2,3,5],
    [3,4,7]
])

In [49]:
ax.reshape(15,2,)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])

In [60]:
scaler = MinMaxScaler(feature_range=(-1,1))
scaler = scaler.fit(np.array(range(31)).reshape(-1,1))

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [65]:
ay_scaled = scaler.transform(ay)
ay_scaled

array([[-0.93333333, -0.86666667, -0.93333333],
       [-0.86666667, -0.8       , -0.66666667],
       [-0.8       , -0.73333333, -0.53333333]])

In [66]:
scaler.inverse_transform(ay_scaled)

array([[1., 2., 1.],
       [2., 3., 5.],
       [3., 4., 7.]])

In [67]:
scaler.transform(ax)

ValueError: Found array with dim 3. Estimator expected <= 2.